### ISSUE TITLE
None of the resp.Body are closed in any of the Oauth2 providers

### ISSUE THREAD

**Issue by asdptkt** [tarent/loginsrv#100]
I've looked into the code and none of them invoking `resp.Body.Close()` in any of the code. Is there any reason for this or could I make a PR for this? Thank you.

**Comment by smancke** [comment]
@asdptkt Thank's for pointing that out!
Yes, a PR would be very nice!

**Comment by JesusIslam** [comment]
@smancke https://github.com/tarent/loginsrv/pull/107

This is the PR.

**Comment by magikstm** [comment]
@smancke this issue was related to #107 which was recently merged and could be closed.
