### ISSUE TITLE
Edge-case that I don't think work as expected - cookie-name

### ISSUE THREAD

**Issue by magikstm** [tarent/loginsrv#103]
I'm unsure if these should be corrected and how they should be.

At the moment, if you do this:
1) Different cookie-name in http.login and http.jwt (with this PR https://github.com/BTBurke/caddy-jwt/pull/39)

If you use `redirect` in http.jwt you are:
1) Redirected to http.jwt's `redirect` page that is in your caddyfile
2) Unable to navigate to any page that is protected by http.login
3) But, you appear to be authenticated

If you don't use `redirect` in http.jwt you are:
1) Displayed a 401 error for the page you navigate to
2) But, you appear to be authenticated if you navigate to `/login`

I think best way to correct the issue could be:
1) Detect such issues when Caddy loads and display a misconfiguration error with details
2) Make authentication fail (possibly with an internal server error)

I would opt for option 1. @smancke please review how these cases should be handled.

**Comment by magikstm** [comment]
I tried to find a solution for this issue and I don't think it'll be an easy fix.

I added details in README.md in PR #106 which could help users if they get similar issues.

@smancke review this issue and feel free to merge PR above if you think it may help in the meantime.

**Comment by magikstm** [comment]
I edited first message in this issue as I couldn't reproduce other issue I mentioned.

I edited PR #106 accordingly.

**Comment by smancke** [comment]
Thx!
Addind this in the documentation is the best we can do with valuable effort.
