### ISSUE TITLE
Caddy - Unexpected behavior on path having the right -login-path prefix, but other characters following it

### ISSUE THREAD

**Issue by magikstm** [tarent/loginsrv#108]
When using Caddy, if you use default `-login-path` being `/login` I created a table with current behavior and what I believe are expected behavior:

| Test no | Path | Current behavior | Expected behavior |
|--|:--:|--:|--:|
| 1 | /login | Displays login page | Displays login page |
| 2 | /LOGIN | Displays login page (if CASE_SENSITIVE_PATH stays "false" which is default) otherwise returns a 404 | Displays login page (if CASE_SENSITIVE_PATH stays "false" which is default) otherwise displays a login page |
| 3 | /loginz | Displays login page | 404 |
| 4 | /login/ | Displays login page | 404 |
| 5 | /login/z | Displays login page | 404 |
| 6 | /loginz/z | Displays login page | 404 |

(*) I'm not 100% sure on behavior for test 2 as I tested on Windows 7 x64 and this OS isn't case sensitive. It would need to be confirmed on another OS.

I think this should be adjusted for Caddy and probably for loginsrv by itself as well.

I think these lines could be adjusted :
Caddy https://github.com/tarent/loginsrv/blob/7a8566d795ccd0337dbd35078817f06ae5edccb1/caddy/handler.go#L42
loginsrv by itself https://github.com/tarent/loginsrv/blob/7a8566d795ccd0337dbd35078817f06ae5edccb1/login/handler.go#L78

@smancke I'll submit a PR for Caddy you can review.

This change would be a change of behavior and should be mentioned in next version if it is modified.

**Comment by smancke** [comment]
Hi @magikstm the login path is by design a prefix.
This is used e.g in case if oauth flows, e.g. `/login/google` etc.

**Comment by smancke** [comment]
But maybe it would make sense to return a 404 for the cases 3 and 6.
So only allow /login and all sub ressources ..?
