### ISSUE TITLE
Include JWT in the redirect URL

### ISSUE THREAD

**Issue by cweagans** [tarent/loginsrv#137]
If I set `backTo=https://myservice.com/somepage?jwt=[token]` on my redirect, I'd like for the JWT to be included in the URL. Is this something that you'd accept a PR for? Or is this functionality already present in loginsrv?

This functionality would open up a lot of opportunities for me to use loginsrv!

**Comment by magikstm** [comment]
What would be the use-case for it?

**Comment by cweagans** [comment]
We manage several hundred websites. I want to do SSO with our Google Apps account, but keeping the Google integration working for thousands of URLs is tiresome (and not easily automated), so the thought is that we'd redirect to loginsrv, do the Google authentication, and then get redirected back to whatever website sent them along to `/login?token=[whatever]`, where the authenticated user would be signed into the website in question.

We're already using loginsrv for some auxiliary services (prometheus, grafana, etc), but we'd love to use it to log into our sites directly.

**Comment by cweagans** [comment]
More generally, the Caddy jwt plugin also supports grabbing the jwt out of the query params. Maybe this would be helpful for the more general case of having one caddy server that handles auth and another that actually serves the protected applications.

**Comment by smancke** [comment]
Not totally sure, if it is a good idea for security-reasons, to include the token in the URL, but since it in an optional feature I would be open of a (testes) P :)

**Comment by cweagans** [comment]
JWTs are designed to be public information. Can you elaborate on what your security concerns are? Just wanna make sure things get built as expected.

**Comment by smancke** [comment]
> JWTs are designed to be public information.
No, only the payload is designed to be public. The JWT with the signature is a secret.

> Can you elaborate on what your security concerns are? 
Things like Caching in the Browser-History, referrer, ..

**Comment by magikstm** [comment]
If misused or if the use-case isn't analyzed properly, it could bring:
- Information disclosure attacks or vulnerabilities
- Injection vulnerabilities

The value of that token will most probably need to be validated a second time to ensure it hasn't been modified by the end user.

It's true that it could be an optional feature, but I'm unsure it would bring more pros than cons in an actual application considering the possible extra layer of security.

I think this would probably be better handled in the application/redirect layer.

Could you elaborate more on the use-case?

How will the token be used and which layer will handle the token?

**Comment by cweagans** [comment]
> No, only the payload is designed to be public. The JWT with the signature is a secret.

That does not reflect my understanding of how JWTs should be used. Why would a cryptographically signed blob of data not be publicly shared? Do you have a reference that you can point at that reflects your position?

> Things like Caching in the Browser-History, referrer, ..

If I first accept that JWTs are not supposed to be public, then this makes sense.

> If misused or if the use-case isn't analyzed properly, it could bring:
>    Information disclosure attacks or vulnerabilities
>    Injection vulnerabilities

Agreed on the former (although my understanding is that JWT claims should be considered public information). Can you elaborate on the latter?

> The value of that token will most probably need to be validated a second time to ensure it hasn't been modified by the end user.

Absolutely -- both loginsrv and whatever other application/server would need to share a JWT secret.

> How will the token be used and which layer will handle the token?

For our application, any user that is a member of our Google Apps account should be able to log into the websites that we manage. The idea is that we'd pass a JWT to our application in the URL, the application would validate the JWT (check that the signature is valid + that the claims reflect what we want) and then log the user into the application. If we just had one instance of this application, we'd authenticate with Google directly, but that becomes pretty difficult to maintain when there are several hundred potential redirect domains to whitelist.

**Comment by smancke** [comment]
>> No, only the payload is designed to be public. The JWT with the signature is a secret.
> That does not reflect my understanding of how JWTs should be used.

It's rather simple: If you use the JWT as a secret to prove to service X that you have done a login at service Y. Than everybody else who has the JWT can also do this prove.

**Comment by averri** [comment]
> JWTs are designed to be public information. Can you elaborate on what your security concerns are? Just wanna make sure things get built as expected.

**BE CAREFUL** This is not true. If someone gets the JWT it's possible to impersonate the owner of the JWT. JWT must be protected at all costs! You should never put the JWT in the URL. This is a security violation.
