### ISSUE TITLE
Has prevent-external-redirects been removed?

### ISSUE THREAD

**Issue by joshstrange** [tarent/loginsrv#162]
I'm getting an error trying to use it in caddy and [I found this commit](https://github.com/tarent/loginsrv/commit/ea40df699b8c3f3fc0f8b1db309ef83e2afc0858) which seems to indicate it has been removed in favor of a whitelist 

Is it just the readme that is out of date on this or am I missing something else?

**Comment by magikstm** [comment]
Your research are right. This parameter has been removed in favor of a whitelist.

The whitelist can be configured with the parameter: -redirect-host-file

https://github.com/tarent/loginsrv/blob/master/login/redirect.go#L97
https://github.com/tarent/loginsrv/blob/master/login/config.go#L154

**Comment by magikstm** [comment]
The parameter: -prevent-external-redirects

Should be removed from the doc.
