### ISSUE TITLE
question: jwt integration

### ISSUE THREAD

**Issue by greenpau** [tarent/loginsrv#171]
The `login` Caddy plugin creates `jwt_token` cookie. The `jwt` Caddy plugin reads the JWT token in the cookie and authorizes access.

The `login` plugin creates JWT token using HMAC algo (HS512). In order to compute an HMAC both plugins need a secret key.

What is the expected interaction between `login` and `jwt` plugin? How do the two make sure that the secret key is in sync? 

cc: @g-w

**Comment by greenpau** [comment]
Stumbled upon the following [comment](https://github.com/BTBurke/caddy-jwt/issues/57#issuecomment-583677683) by @roblabla. It answers my question:

    caddy-jwt and loginsrv have a cool "feature" where loginsrv will automatically generate a random jwt 
    secret if none are set in the Caddyfile, and store it in the JWT_SECRET environment variable. When 
    caddy-jwt later parses its own directive, it will use the secret found in the JWT_SECRET environment 
    variable if none are configured.

    Now, this is obviously ordering-dependent. The login directive must be parsed before the jwt
    directive for this to work. Which, obviously, doesn't really work out reliably well. I'm not sure
    how caddy parses the directive and how everything is ordered, but when I tried it,
    caddy-jwt didn't find any JWT_SECRET because it was parsed before loginsrv

**Comment by roblabla** [comment]
FWIW the second paragraph refers specifically to my attempt at making that feature work in my Caddy2 fork of the two modules. It works with 100% reliability in the Caddy1 version found in this repo.
