### ISSUE TITLE
Share JWT token across subdomains

### ISSUE THREAD

**Issue by cceyda** [tarent/loginsrv#172]
[with caddy-plugin] I want to be able to access `y.domain.com` and `x.domain.com` with the same token.
My use case is; 
I have some static files at `y.domain.com` that are being loaded inside` x.domain.com`.
What would be the correct/secure setup for this? I'm guessing I might be able to set this up using the redirect_host_file, but have no idea how? or maybe with this [PR](https://github.com/tarent/loginsrv/pull/124) ?

My current settings:
```
x.domain.com{
....
	jwt {
		path /
		redirect /login?backTo={rewrite_uri}
	  }
	login {
	  htpasswd file=[pass_file_path]
	  redirect_check_referer false
	  redirect_host_file [redirect_file_path]
}
}
y.domain.com{
....
	jwt {
		path /
		redirect /login?backTo={rewrite_uri}
	  }
	login {
	  htpasswd file=[pass_file_path]
	  redirect_check_referer false
	  redirect_host_file [redirect_file_path2?]
	}
}
```

**Comment by magikstm** [comment]
Should be doable with cookie-domain depending on versions you currently use.

Ref: https://github.com/tarent/loginsrv/issues/102

I'll try to add an example to the doc on the main page this weekend.

**Comment by averri** [comment]
Hi @cceyda, your backend that creates the jwt cookie neet to set its domain to `domain.com`. In this way, the cookie will be valid for all subdomains of `domain.com`.

**Comment by cceyda** [comment]
Thank you~ I will close this now.
