### ISSUE TITLE
2fa/TOTP support

### ISSUE THREAD

**Issue by cktang88** [tarent/loginsrv#177]
Is there any way to get 2fa/TOTP to work with this?

**Comment by g-w** [comment]
Hello @cktang88, 

currently there is no direct support for 2FA in loginsrv and no plans to implement this. If you use OAuth2 (ie. google, facebook) the methods supported by the provider are supported. Further you could implement an [Httpupstream](https://github.com/tarent/loginsrv#httpupstream) service which supports 2FA. 

In general this feature is (in my opinion) out of the scope of this project.

If you have any suggestion how to implement this as a feature of loginsrv, please, reopen this issue. I will close it for now.
