### ISSUE TITLE
Allow user to supply own login form template

### ISSUE THREAD

**Issue by captncraig** [tarent/loginsrv#2]
It would be nice if the user could supply their own login form template. I'd recommend

```
login / {
   loginTemplate mylogin.html
}
```

They could do a simple static button if need be, or something more complicated using a go template. Should look it up relative to the site's root probably. In any case, should probably cache the template, rather than parsing it each time.

**Comment by mholt** [comment]
I prefer `login_template` over `loginTemplate`. ;)

**Comment by smancke** [comment]
Now I made just `template`.

But I did not find a way to resolve the template path relative to the webroot or caddyfile.
@mholt Is there a convention, how relative path arguments should be interpreted or resolved in caddy plugins?

**Comment by captncraig** [comment]
As an additional option, what if I just say `template pass` or something, so that it just serves gets to `/login` from whatever application or files are naturally underneath. Would allow my proxied app to just have its own login page.

**Comment by smancke** [comment]
@captncraig Yes, good idea! 
But I have to think about it a little bit, because the _pass_ option would make  no sense in the loginsrv standalone usecase.

**Comment by mholt** [comment]
@smancke You can grab the site root from the SiteConfig through the Controller. Typically things are relative to site root; Caddyfiles aren't always files on disk, so never do anything relative to the Caddyfile. The only other option is present working directory (which often varies or is not even known by some server admins, sigh). So go with site root.

**Comment by smancke** [comment]
Implemented now, with lookup relative to the site root.
