### ISSUE TITLE
Caddy usage - htpasswd file isn't reloaded (on insert, on update or on delete)

### ISSUE THREAD

**Issue by magikstm** [tarent/loginsrv#20]
Tested on Windows 7 x64:

Launched with: go run main.go

My caddyfile is:

> http://localhost:8080 {
> 
>   log stdout  
>   root C:\[path to demo]\demo\webroot
>   ext .html
>   header /members Cache-Control "no-cache, no-store, must-revalidate"
>   
>   jwt {
>     path /members
>     redirect /login
>   }
> 
>   login {
>         success_url /members/private
>         htpasswd file=passwords
>   }
>   
> }

If I:
1) Add a user
2) Remove a user
3) Update a user's password

htpasswd file isn't reloaded.

Another service on my server "adds", "removes" or "updates" users on the htpasswd file I wish to use and I would want loginsrv to use the current credentials available in the file instead of the content it had on launch.

**Comment by magikstm** [comment]
Is this enhancement planned to be completed soon?

It is as mentioned above in apache and nginx.

If not and if it is a feature that may be added, I could maybe try to contribute a fix for it. I'm not that good in Go though (I'm more a .Net or PHP developer). If possible, please provide me some basic specs on how you would wish for it to be completed.

**Comment by smancke** [comment]
I like the feature, but I'm a little bit short on time, currently.
So, if you want to give it a try, this would be fine .. if it's not perfect, I 'll overwork it afterwards.

How to implement it:
- Store the modification timestamp (os.Stat()) after parsing the file
- Create a method reloadIfChanged which compares the current and the stored timestamp an calls parse again. This method can be called before Authenticate
- The changes an the read of the map have to be synchronized with a `sync.RwMutex`
- Create a test for it

**Comment by magikstm** [comment]
Thanks for the info.

I submitted PR #21 for it. It's probably incomplete though.

**Comment by magikstm** [comment]
I've just been notified of the merge. Thanks for finalizing the tests for me. I didn't know how to fully do it. I'll review it to learn from it.

Thanks a lot @smancke . I really like this feature.
