### ISSUE TITLE
Submit to Caddy website

### ISSUE THREAD

**Issue by mholt** [tarent/loginsrv#22]
Hey @smancke do you have plans to publish this to the Caddy website? Since your directive was added to Caddy and released, it's ready to be used by everyone.

**Comment by smancke** [comment]
Hi @mholt, yes, definitely!
My plan is to do this in the next week, because I want check it carefully and I'm very busy these days.

**Comment by mholt** [comment]
Sounds great! Let me know if something doesn't work or you have any questions.

**Comment by smancke** [comment]
I have published the plugin, and done some basic tests.
@magikstm Please also give me your feedback, if also everything works for you.

I'll do an announcement in the caddy forum, tomorrow.

@mholt The developer portal is very cool and worked very nice!
Although, I have some minor suggestions/feedback:
* On editing the plugin details page, it is not clear, where I can use markup and not all my markup worked.
* I used the direct download url `https://caddyserver.com/download/linux/amd64?plugins=..` the first time. My expectation was to get a binary and I was wondering that I could not execute the file. Maybe it would be good to control by a parameter if a tar.gz or only the binary should be returned.
* My first deployment failed with 'golang unexpected directory layout', which seems to be a known go 1.8 problem. The second deployment worked well.

**Comment by magikstm** [comment]
I added "http.jwt" and "http.login" with the install package and tested functionalities I'm using at the moment on Windows 7 x64.

Everything I use with htpasswd files work well.

Thanks a lot.
