### ISSUE TITLE
Caddyfile path parameter is a bit confusing

### ISSUE THREAD

**Issue by captncraig** [tarent/loginsrv#3]
I had to do some digging to see why I need to supply `login / {` at all. I first thought that was the "protected" paths, but since this does no authorization at all, that wasn't it.

Turns out that is the location to mount the "/login" routes. Does that really need to be a **required** top level argument? What if it was a simple config line `login_path` that defaults to `/login` or something like that?

**Comment by smancke** [comment]
fixed
