### ISSUE TITLE
Brute force protection on htpasswd login backend

### ISSUE THREAD

**Issue by magikstm** [tarent/loginsrv#31]
I've been getting some brute force attempts recently on the htpasswd login protection used with caddy and loginsrv. I've been looking for a way to mitigate these.

I did get such attacks from time to time with apache. I use fail2ban for these on apache.

Would there be a free solution that may be added that may fit within the scope of the project that may be used on a static site solely with html, css and javascript?

I was thinking about Google Recaptcha on the login page as it seems relatively well-known:
https://www.google.com/recaptcha/intro/

Or is there a solution available at the moment?

It wouldn't have to be 100% bullet-proof, but I'm looking for something that would help mitigate these.

**Comment by magikstm** [comment]
I'm open to any solution:
- Another Caddy plugin
- An external tool
- An integration in this plugin
- etc.

It's not an issue per-se, but I felt it was best here as others may have similar needs. Or there may be a way currently that I don't know and it may help others.

I've looked and I've found a few captcha plugins available in Go (a few specifically with google recaptcha). It may not be the best solution though. I'm not an expert on these. There may be better solution available that are also user-friendly.

Feel free to mark it as closed if it doesn't fit within the scope of the project.

**Comment by smancke** [comment]
The Bcrypt algorythm solves this problem by adding a compute time to the password check.
You should generate your passwords with the option `-B -C 15` when creating with htpasswd:

`
        -B     Use bcrypt encryption for passwords. This is currently considered to be very secure.

       -C     This  flag  is  only allowed in combination with -B (bcrypt encryption). It sets the computing time used for the bcrypt algorithm (higher is more secure
              but slower, default: 5, valid: 4 to 31).
`

Maybe we should mention this in the documentation.

**Comment by magikstm** [comment]
Thanks @smancke.

I read on it following your suggestion. I'll have to learn more on it and test it with my hardware.

I can control new users and passwords, but I'm not using it currently. I'll have to read on how I could add it to my current workflow and how I could convert my current user:password combinations to it.

**Comment by smancke** [comment]
We are currently considering -C 15 as save enough

**Comment by magikstm** [comment]
Thanks @smancke. It works really better than I expected even with 1000 users. It takes a reasonable time if the password is the right one or if it's wrong.

I'll close this issue.

I used that code in PHP to generate usernames and passwords in case it may help others:

`<?php
ini_set('max_execution_time', 5000);

//usernumber start variable
$start = 0;

//bcrypt cost
$bcryptOptions = ['cost' => 15];

for ($i = 1; $i <= 1000; $i++)
{
	//user data
	$usernumber = $start + $i;
	$user = "user{$usernumber}";
	$password = generateRandomString();
	$hash = password_hash($password, PASSWORD_BCRYPT, $bcryptOptions);
	
	//text to append to file
	$txt = "{$user}:{$password}:{$hash}";
	
	//append text to file
	file_put_contents('users.txt', $txt.PHP_EOL, FILE_APPEND | LOCK_EX);
}

//generates a random string of length in parameter
function generateRandomString($length = 10)
{
    $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $charactersLength = strlen($characters);
    $randomString = '';
    for ($i = 0; $i < $length; $i++)
	{
        $randomString .= $characters[rand(0, $charactersLength - 1)];
    }
    return $randomString;
}
?>`

**Comment by smancke** [comment]
ok, great!
