### ISSUE TITLE
Caddy - Use {user} placeholder for logs

### ISSUE THREAD

**Issue by magikstm** [tarent/loginsrv#32]
Request based on these:
https://github.com/mholt/caddy/pull/1542
https://github.com/mholt/caddy/issues/1543

It's still under development, but it'll probably be possible with lines similar to these:
```
// Capture username into {user} placeholder for caddyfile log directive
	// ex:  log / stdout "{remote} - {user} [{when}] {method} {uri} {proto} {status} {size}"
	*r = *r.WithContext(context.WithValue(r.Context(),
httpserver.RemoteUserCtxKey, username))
```

**Comment by jamesboswell** [comment]
@magikstm see https://github.com/mholt/caddy/pull/1937  

```go
	repl := httpserver.NewReplacer(r, nil, "-")
	repl.Set("user", username)
```

**Comment by magikstm** [comment]
I'll submit a PR in a few hours to add this feature.

**Comment by magikstm** [comment]
Following the merge of #52 I'll close this issue.
