### ISSUE TITLE
Correct 'scope' for Google OAuth2

### ISSUE THREAD

**Issue by freb** [tarent/loginsrv#42]
I'm trying to get the Google OAuth2 backend working with Caddy, but I believe I am stuck on finding the right value for the scope parameter. These are what I've tried:

- `profile`
- `https://www.googleapis.com/auth/plus.login`
- `https://www.googleapis.com/auth/plus.me`

but they all error with:

    error="invalid google response: no email address returned."

Any thoughts on the scope I should be using?

Just to provide some feedback, I had other issues I ran into along the way, like not having the Google+ API enabled in my Google account, but I had to custom compile Caddy to get this error out of loginsrv by reading the response body and adding print statements here: https://github.com/tarent/loginsrv/blob/master/oauth2/google.go#L46

Thanks for the plugin. This seems to be exactly what I've been waiting for.

**Comment by chriswessels** [comment]
@freb Try with the `email` scope

**Comment by freb** [comment]
Thank you @chriswessels, that worked! I guess maybe it should have been obvious by the error message.

Thanks again.

**Comment by chriswessels** [comment]
My pleasure @freb 😄
