### ISSUE TITLE
Restrict access by OAuth2 domain

### ISSUE THREAD

**Issue by freb** [tarent/loginsrv#43]
My goal is to be able to limit access to some backend applications using Google OAuth2. I'm a Google Apps user and would like to start by limiting access by domain. Using `loginsrv` with `caddy-jwt` there doesn't seem to be a way to limit access based on the email address domain. It seems it would require support for regex in the caddy-jwt plugin for field values or perhaps I'm missing a simpler solution.

I'm wondering if parsing out the domain and including it in the JWT is something that would be in-scope for this plugin. Or if you would be willing to optionally support pulling information from any of the additional scopes that could also be helpful in limiting access, such as user groups: https://developers.google.com/admin-sdk/directory/v1/guides/authorizing

I'd like to tackle this in the most reusable way in case I can contribute some code.

Thanks!

**Comment by smancke** [comment]
Hi @freb,
it is definitely in scope for loginsrv to extend it in this way.
Currently I have no good idea, about a common structure of the UserInfo Object.
There needs to be a structure, which is suitable for a broader set of OauthProvider (z.g. google, github, facebook, Keycloak and others)

Also see #8 and #37 for that.

**Comment by freb** [comment]
I read the other two issues, and either of them would solve my use case. I'm always a fan of being able to inject custom functionality, weather through calling an external script, callback function, plugin, etc. It allows you to do more than just manipulate the UserInfo.

I'm really only familiar authenticating against the Google API and haven't looked much into what other information would be nice to have in the UserInfo object. If I get some time, I'll see if I can come up with some ideas.

**Comment by lhopki01** [comment]
Hi I've made a change to include domain for google oauth.
https://github.com/tarent/loginsrv/pull/48

**Comment by freb** [comment]
Thanks for this @lhopki01. I ended up just listing the full email addresses individually so kind of dropped the ball on this. Since its now fixed I'm closing the issue.
