### ISSUE TITLE
OpenIdConnect/Keycloak Support

### ISSUE THREAD

**Issue by bs-matil** [tarent/loginsrv#44]
Would be greate to implement openidconnect in addition of the proprietary outh2 flows of github and google. Also this would then integrate with keycloak and enable a broad amount of integration scenarios. Like serving LDAP/SAML via keycloak instead of implementing everything here again.

**Comment by uchagani** [comment]
Any movement on this?

**Comment by florentsolt** [comment]
Would be awesome!

**Comment by bs-matil** [comment]
@florentsolt  if you look for similar functionality have a look at keycloak gatekeeper
