### ISSUE TITLE
Multiple forward slashes in paths may pass-through security with htpasswd

### ISSUE THREAD

**Issue by magikstm** [tarent/loginsrv#46]
related to https://github.com/mholt/caddy/issues/1859.

With this minimal caddyfile:
```
http://localhost:8080 {

  log stdout  
  root C:\webroot
  ext .html
  header /members Cache-Control "no-cache, no-store, must-revalidate"
  
  jwt {
    path /members
    redirect /login
  }

  login {
        success_url /members/private
        htpasswd file=passwords
  }
}
```

multiple forward slashes may pass-through the security.

I did these tests:
1) http://localhost:8080/members/1.jpg (redirects to login)
2) http://localhost:8080//members/1.jpg (passes through login and shows the image)
3) http://localhost:8080//members//1.jpg (passes through login and shows the image)
4) http://localhost:8080/members//1.jpg (redirects to login)

It's a critical vulnerability.

**Comment by smancke** [comment]
Hey @magikstm, that looks critical.
But if so, than it would be a bug in jwt-Plugin, not in loginsrv, right?
@BTBurke, please take a look

**Comment by magikstm** [comment]
I think it's a bug in Caddy as reported by @hstaugaard (see https://github.com/mholt/caddy/issues/1859).

Unsure though. Just took the time to read it, test it and confirm it.

It also seems critical to me.

**Comment by smancke** [comment]
Ok, I'll close it here, because the in loginsrv I can't do anything for that.
It has to be solved in caddy or the jwt plugin.
