### ISSUE TITLE
Oauth2

### ISSUE THREAD

**Issue by Danielhiversen** [tarent/loginsrv#50]
I have the following config:

```
login {
         google client_id=XXXXX.apps.googleusercontent.com,client_secretXXXXXX,scope=https://www.googleapis.com/auth/userinfo.email
}
```

How can specify which user to have access?

**Comment by Danielhiversen** [comment]
I guess this should work:
`
    allow email xxx@xxxx.com
`

But I am getting this error message: 
`ERRO[0137]                                               error="got http status 403 on google get user info" type=application`
I have also tried with `scope=email`

**Comment by lhopki01** [comment]
@Danielhiversen scope `scope=https://www.googleapis.com/auth/userinfo.email` is correct but I think from what I remember that I had to enable the api if you're using a custom google domain.

https://support.google.com/a/answer/60757?hl=en

**Comment by smancke** [comment]
Works for me also.
@Danielhiversen Please reopen, if you still have a problem.
