### ISSUE TITLE
Bitbucket Oauth2 support

### ISSUE THREAD

**Issue by afdecastro879** [tarent/loginsrv#51]
I've working with this library for a couple of months, but now we need Bitbucket Oauth2 support. Would be nice to add it to the providers list.

I can actually start working on this.

**Comment by smancke** [comment]
Hey @afdecastro879, would be cool to have a Bitbucket provider. Of course, I would welcome a PR for this :)

**Comment by smancke** [comment]
done :)

**Comment by afdecastro879** [comment]
Thanks a lot :)
