### ISSUE TITLE
google: Configuration to restrict to specific domain

### ISSUE THREAD

**Issue by dobegor** [tarent/loginsrv#57]
A special paramater [hd](https://developers.google.com/identity/protocols/OpenIDConnect#hd-param) ("hosted domain") can be used to restrict authentication for specific domain, i.e. email@yourcompany.com.

It would be a very nice feature to setup some in-home only services behind a loginsrv+caddy.

**Comment by lhopki01** [comment]
@dobegor This can be done for google oauth.  It adds the domain to the jwt and you can then restrict using the jwt block in the caddy config with `allow domain yourcompany.com`

Are you using google oauth?

**Comment by dobegor** [comment]
@lhopki01 could you please provide an example configuration?
Also, AFAIK, this will work, but if you pass additional `hd` parameter login form in google won't even allow to enter email with another domain name.

**Comment by lhopki01** [comment]
@dobegor 
```
      jwt {
        path /
        allow domain yourcompany.com
      }
      login {
        google "client_id=xxxxxxx,client_secret=xxxxxxx,scope=https://www.googleapis.com/auth/userinfo.email"
      }
```
I don't quite understand what you meant in the second section.

**Comment by dobegor** [comment]
https://snag.gy/Dvts5w.jpg

If you pass the `hd` paramater, Google's sign-in form will only allow you to login using corporate account.

**Comment by lhopki01** [comment]
I don't think that the plugin is using the open connect api.

**Comment by dobegor** [comment]
@lhopki01 yeah, I was assuming this for some reason.
I get this error: `got http status 403 on google get user info` when trying to log in via google.

Scope: `scope=https://www.googleapis.com/auth/userinfo.email`
Authorized redirect URLs are set correctly.

**Comment by dobegor** [comment]
As this has nothing to do with domain-specific login, I'm closing this issue.
