### ISSUE TITLE
oauth2: got http status 403 on google get user info

### ISSUE THREAD

**Issue by dobegor** [tarent/loginsrv#58]
Caddyfile:
```
localhost:3000 {
  proxy / localhost:3040
  jwt {
    path /
    allow domain readdle.com
  }
  login {
    google "client_id=***,client_secret=***,scope=https://www.googleapis.com/auth/userinfo.profile"
  }
}
```

Upon login it shows "Internal error" and an error in log: `oauth2: got http status 403 on google get user info`

Also tried these scopes: `https://www.googleapis.com/auth/plus.me`, `https://www.googleapis.com/auth/plus.login` with same effect.

Client ID and Client Secret are created for a fresh sample project. Same Client ID and secret work  for [bitly/oauth2_proxy](https://github.com/bitly/oauth2_proxy), but I'd prefer to use caddy+loginsrv in our setup.

**Comment by domudall** [comment]
Also having this issue, tried with the following permissions (both with and without custom domain):

```
email
profile
openid
https://www.googleapis.com/auth/userinfo.email
https://www.googleapis.com/auth/userinfo.profile
```

Custom domain has API's enabled, and the OAuth app in Google Cloud has no additional settings that would change any behaviour.

**Comment by dobegor** [comment]
I've managed to fix this, @domudall 
I've enabled Google Plus API and Google People API. It worked after a minute or so. Works great for me now.

**Comment by smancke** [comment]
@dobegor Good to here that!!
Maybe you could file a PR for the README, so that others do not have to figure that out by there self?

**Comment by dobegor** [comment]
@smancke sure, will do that. Just need to check if both APIs are required to work. Google's OAuth 2 Scopes doc has absolutely zero info on this, unfortunately.

**Comment by domudall** [comment]
Amazing, thanks all. Managed to get it working with just the Google+ API (tried just People first, then disabled). Here's a direct link to enable for anyone who finds this issue before the README PR: https://console.cloud.google.com/apis/library/people.googleapis.com/

**Comment by kmonsoor** [comment]
People from future,

Please enable Google's **[Plus API](https://console.cloud.google.com/apis/library/plus.googleapis.com/)**, NOT [people API](https://console.cloud.google.com/apis/library/people.googleapis.com/). This is true when you need only the email of the user.

As the `scope` use `https://www.googleapis.com/auth/userinfo.email` on the line  
`google "client_id=......,client_secret=.....,scope=https://www.googleapis.com/auth/userinfo.email`   inside the `login { }` block on Caddyfile.

You're welcome.

**Comment by rochdev** [comment]
What is the replacement API now that Google+ has been deprecated? It's very unclear in Google's own documentation.

**Comment by smancke** [comment]
Hi @rochdev 
as mentioned in the README:

> ** Attention: Update to v1.3.0 for Google Login Update !!!! **
> Google will stop support for the Google+ APIs. So we changed loginsrv to use the standard oauth endpoints for Google login. Please update loginsrv to v1.3.0 if you are using google login.
