### ISSUE TITLE
Is loginsrv 1.2.4 available in Caddy 0.10.13?

### ISSUE THREAD

**Issue by debackerl** [tarent/loginsrv#79]
Hello,

Is loginsrv 1.2.4 available in Caddy 0.10.13? I need to use new dynamic redirects and user claims files, but when using those features, Caddy 0.10.13 says it can't process my config:

Here is my config:

`        login {
                login_path /login
                google client_id={$GOOGLE_CLIENT_ID},client_secret={$GOOGLE_CLIENT_SECRET},scope=openid%20email
                redirect true
                redirect_query_parameter redirect_uri
                redirect_check_referer false
                cookie_http_only true
                cookie_name jwt_token
                cookie_domain XXXX
                user_file /etc/caddy/users.yml
        }
`

Thank you :-)

**Comment by smancke** [comment]
should work now ..

**Comment by debackerl** [comment]
Indeed! Thank you so much!

**Comment by kvnndr0** [comment]
login { login_path /login google client_id={$GOOGLE_CLIENT_ID},client_secret={$GOOGLE_CLIENT_SECRET},scope=openid%20email redirect true redirect_query_parameter redirect_uri redirect_check_referer false cookie_http_only true cookie_name jwt_token cookie_domain XXXX user_file /etc/caddy/users.yml }
