### ISSUE TITLE
Need more explanation on `domain` for userfile.yml

### ISSUE THREAD

**Issue by ducdigital** [tarent/loginsrv#82]
Hello guys,

What exactly is the `domain` that written in the example of your user file?

Is it the hostname that the user is signing on, or is it the domain of the user's email return back from oAuth?

Beside is there any way to validate user's email domain? something like validate the `company.info` part of `user1@company.info`?

Thank you

**Comment by smancke** [comment]
The google oauth provider fills the JWT object with some data, which is returned by the `/people/me` endpoint. If you match against the domain in the userfile, it is matched against this fields.
See also: 
https://github.com/tarent/loginsrv/blob/e482109fc416fb8678befb27336ab5d08ff10252/oauth2/google.go#L74

loginsrv does not do any validations. But e.g. if you use the caddy-JWT plugin, you can validate the claims of the token with the `allow domain company.info`.

The userfile is meant for more complex scenarios. e.g. to add a special role attribute to all users from a specific domin.
