### ISSUE TITLE
oauth callback parameters not handled for errors

### ISSUE THREAD

**Issue by philpennock** [tarent/loginsrv#83]
While setting up a new site, as expected there was a mismatch in the redirect URI (next step was to fix that, testing the first step).  What surprised me is that nothing was shown in the login page generated by loginsrv, using the caddy plugin, when I was redirected back to the base site.

The callback URL parameters included:
* `error=redirect_uri_mismatch` 
* `error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.`
* `error_uri=....`
* `state=....`

It would be good if this scenarios could be handled cleanly.

**Comment by smancke** [comment]
Can't reproduce this:
When I simulate this, I get a red error box with the text: _'Internal Error. Please try again later. '_
