### ISSUE TITLE
gitlab provider?

### ISSUE THREAD

**Issue by likewhatevs** [tarent/loginsrv#88]
@smancke - Awesome Library.

Would you be open to an MR enabling the use of Gitlab as an oauth2 provider?

If so, is there a way you recommend I get the domain name of the Gitlab instance to `Provider`?

I'm not seeing any clean ways to do this.

**Comment by smancke** [comment]
Hi  @likewhatevs,
Sorry I forgotto come back to this after my summer holiday.

Yes, I would definitely be open to a Gitlab provider.

The domain could be supplied similar to the scope parameter and could than be used to set the Auth and Token URLs, see here:
https://github.com/tarent/loginsrv/blob/908622dcb707ceaef94ebb3da57ffa5c019dc937/oauth2/manager.go#L90

**Comment by asdptkt** [comment]
https://github.com/tarent/loginsrv/pull/92
