### ISSUE TITLE
PHP $_SERVER['REMOTE_USER'] not set

### ISSUE THREAD

**Issue by xombiemp** [tarent/loginsrv#94]
I've been able to get Caddy with http.login and http.jwt working with htpasswd.  I'm presented with a login page and after I authenticate I can see the resources.

I'm using fastcgi with php-fpm to server php files.  The app I'm running relies on $_SERVER['REMOTE_USER'] to get the logged in user, but this variable is not set after I login and try to print it from php.

Is there anything I can do to make sure this variable is populated with the name I authenticated with?

**Comment by magikstm** [comment]
Thanks for mentioning this issue. I'm adding this feature to loginsrv.

I'll submit a PR in 1-2h.

**Comment by magikstm** [comment]
PR #95 should be reviewed and merged soon. In the meantime, if you can compile yourself, add this PR to your build of Caddy.

**Comment by xombiemp** [comment]
Awesome! Thanks for looking at this so quick. I’ve not compiled, but I’ll look into that.
