### ISSUE TITLE
redirect backTo not working correctly

### ISSUE THREAD

**Issue by xombiemp** [tarent/loginsrv#97]
I'm trying to configure a dynamic redirect on successful login.  My Caddyfile looks like
```
my.domain.com {
    root /var/www
    header / Cache-Control "no-cache"

    fastcgi / /var/run/php-fpm/php-fpm.sock php

    jwt {
      path /
      except /favicon.ico
      redirect /login?backTo={rewrite_uri}
    }

    login {
      htpasswd file=/var/lib/caddy/passwd
    }
}
```

From what I can gather the referrer host must match the current request host by default.
Here what my request headers look like:
<img width="544" alt="image" src="https://user-images.githubusercontent.com/690710/49768659-4d7cfc80-fc9a-11e8-80f4-6b8d0b81d152.png">
You can see that the host and the referrer host are the same.  However, the redirect is not working and in the log I am seeing:
```
"2018-12-10T23:20:29Z" level=warning msg="redirect from referer domain: '', not matching current domain 'ec2.parkerspot.com'" type=application
```
This seems like a bug.  Am I missing something?

**Comment by magikstm** [comment]
Try changing to this:
```
jwt {
      path /
      except /favicon.ico
      redirect /login
}
```

Then try clicking on a link like this one:
`<a href="/login?backTo=/rutorrent/">login with backTo</a>`

Worked for me locally with Windows 7 x64.

Then adjust as needed.

If it doesn't work please share both your client browser and OS as well as your server OS.

**Comment by magikstm** [comment]
Ref: https://github.com/tarent/loginsrv#redirects

You can use these two to adjust behavior:
```
--redirect-check-referer=false
```
```
--redirect-host-file=/some/domains.txt
```

If you simply browse to a URI without actually clicking a link your referer would be empty. Accepting that by default would open the user to phishing or login attacks even if user visited site before from same session.

**Comment by xombiemp** [comment]
Ok, thank you for your response.  I understand the behavior now and can see that this is how it was designed to work to be more secure by default.  I will add redirect_check_referer false so that browsing directly to a URI redirects correctly.
Thanks!
